[book]
title = "ArkForge Astra"
authors = ["Elham Aryanpur"]
language = "en"
src = "./src"

[build]
build-dir = "../../../docs/docs/latest"

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/ArkForgeLabs/Astra"
site-url = "/docs/latest/"
edit-url-template = "https://github.com/ArkForgeLabs/Astra/edit/main/src/docs/latest/{path}"

[output.html.playground]
copyable = true
copy-js = true
