name: Other Platforms

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Other Platforms
    runs-on: ubuntu-latest
    environment: production

    env:
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        id: cache-cargo-restore
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - run: |
          rustup toolchain install 1.88.0
          rustup override set 1.88.0
          rustup show

      - run: cargo install cross --git https://github.com/cross-rs/cross

      # ============================================================ #
      # ========================== RISC-V ========================== #
      # ============================================================ #

      - name: LuaJIT
        run: cross build --release --target riscv64gc-unknown-linux-gnu --features default
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-luajit-riscv-amd64
          tag: ${{ github.ref }}

      - name: LuaJIT 52
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features luajit52
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-luajit52-riscv-amd64
          tag: ${{ github.ref }}
      
      - name: Luau
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features luau
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-luau-riscv-amd64
          tag: ${{ github.ref }}

      - name: Lua 5.1
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features lua51
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-lua51-riscv-amd64
          tag: ${{ github.ref }}
      
      - name: Lua 5.2
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features lua52
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-lua52-riscv-amd64
          tag: ${{ github.ref }}
      
      - name: Lua 5.3
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features lua53
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-lua53-riscv-amd64
          tag: ${{ github.ref }}
      
      - name: Lua 5.4
        run: cross build --release --target riscv64gc-unknown-linux-gnu --no-default-features --features lua54
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/riscv64gc-unknown-linux-gnu/release/astra
          asset_name: astra-lua54-riscv-amd64
          tag: ${{ github.ref }}

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://github.com/ArkForgeLabs/Astra
          environment: production
